# Nobara Install Profiles — custom Ventoy GRUB entries
# Auto-generated by nobara-install.sh — do not edit by hand
#
# Placeholders substituted at deploy time:
#   NOBARA_ISO_FILENAME  — e.g. Nobara-43-GNOME-NV-2026-04-25.iso
#   NOBARA_ISO_CDLABEL   — e.g. Nobara-43  (ISO volume label)
#
# ┌─────────────────────────────────────────────────────────────────────────┐
# │  [f]  Vollinstallation  →  bootet ISO, Anaconda installiert frisch      │
# │  [t]  Theme + Bash      ─┐                                              │
# │  [h]  Headless vLLM     ─┤ laufen auf BESTEHENDEM Nobara:               │
# │  [v]  vLLM only         ─┘ nobara-provision.sh vom USB starten          │
# └─────────────────────────────────────────────────────────────────────────┘
#
# Disk-Override (nur für [f]): Im GRUB-Menü (e) und an linux-Zeile anhängen:
#   inst.disk=nvme1n1      (z.B. zweite NVMe)
#   inst.disk=sdb          (z.B. zweite SATA-Disk)
# Ohne Override: größte interne Disk wird automatisch gewählt.

# ── [m] VM-Test — bootet ISO, installiert in KVM-VM (vda, 80GB) ─────────────
menuentry "Nobara -- [m] VM-Test           (ISO-Boot → Anaconda → KVM/virtio)" --hotkey=m {
    search --no-floppy --label --set=root Ventoy
    set isofile="/NOBARA_ISO_FILENAME"
    loopback loop $isofile
    linux  (loop)/images/pxeboot/vmlinuz inst.stage2=hd:LABEL=Ventoy:${isofile} nomodeset inst.ks=hd:LABEL=Ventoy:/kickstart/nobara-vm.ks
    initrd (loop)/images/pxeboot/initrd.img
}

# ── [f] Vollinstallation — bootet ISO, installiert frisches System ────────────
menuentry "Nobara -- [f] Vollinstallation  (ISO-Boot → Anaconda → frisches System)" --hotkey=f {
    search --no-floppy --label --set=root Ventoy
    set isofile="/NOBARA_ISO_FILENAME"
    loopback loop $isofile
    linux  (loop)/images/pxeboot/vmlinuz inst.stage2=hd:LABEL=Ventoy:${isofile} nomodeset inst.ks=hd:LABEL=Ventoy:/kickstart/nobara-full.ks
    initrd (loop)/images/pxeboot/initrd.img
}

# ── [t] Theme + Bash — Provisioner auf bestehendem System starten ────────────
menuentry "Nobara -- [t] Theme + Bash       (bestehende Installation → Provisioner)" --hotkey=t {
    echo ""
    echo "Dieses Profil installiert kein neues System."
    echo "Im laufenden Nobara ausfuehren:"
    echo ""
    echo "  sudo bash /run/media/USER/Ventoy/nobara-provision.sh --profile theme-bash"
    echo ""
    echo "Taste druecken um fortzufahren ..."
    sleep -1
}

# ── [h] Headless vLLM (Podman) — Provisioner auf bestehendem System ──────────
menuentry "Nobara -- [h] Headless vLLM      (bestehende Installation → Provisioner)" --hotkey=h {
    echo ""
    echo "Dieses Profil installiert kein neues System."
    echo "Im laufenden Nobara ausfuehren:"
    echo ""
    echo "  sudo bash /run/media/USER/Ventoy/nobara-provision.sh --profile headless-vllm"
    echo ""
    echo "Taste druecken um fortzufahren ..."
    sleep -1
}

# ── [v] vLLM only — Provisioner auf bestehendem System ───────────────────────
menuentry "Nobara -- [v] vLLM only          (bestehende Installation → Provisioner)" --hotkey=v {
    echo ""
    echo "Dieses Profil installiert kein neues System."
    echo "Im laufenden Nobara ausfuehren:"
    echo ""
    echo "  sudo bash /run/media/USER/Ventoy/nobara-provision.sh --profile vllm-only"
    echo ""
    echo "Taste druecken um fortzufahren ..."
    sleep -1
}
