# Nobara Install Profiles — custom Ventoy GRUB entries
# Auto-generated by nobara-install.sh — do not edit by hand
#
# Placeholders substituted at deploy time:
#   NOBARA_ISO_FILENAME  — e.g. Nobara-43-GNOME-NV-2026-04-25.iso
#   NOBARA_ISO_CDLABEL   — e.g. Nobara-43  (ISO volume label)
#
# Hotkeys: [f] Full  [t] Theme  [h] Headless  [v] vLLM-only
#
# Disk-Override: Im GRUB-Menü (e) drücken und an die linux-Zeile anhängen:
#   inst.disk=sdb          (z.B. zweite SATA-Disk)
#   inst.disk=nvme1n1      (z.B. zweite NVMe)
# Ohne Override: größte interne Disk wird automatisch gewählt.

menuentry "Nobara -- [f] Vollinstallation  (GNOME + NVIDIA + AI + vLLM)" --hotkey=f {
    search --no-floppy --label --set=root Ventoy
    set isofile="/NOBARA_ISO_FILENAME"
    loopback loop $isofile
    linux  (loop)/images/pxeboot/vmlinuz root=live:CDLABEL=NOBARA_ISO_CDLABEL rd.live.image nomodeset inst.ks=hd:LABEL=Ventoy:/kickstart/nobara-full.ks
    initrd (loop)/images/pxeboot/initrd.img
}

menuentry "Nobara -- [t] Theme + Bash       (GNOME + WhiteSur, kein AI)" --hotkey=t {
    search --no-floppy --label --set=root Ventoy
    set isofile="/NOBARA_ISO_FILENAME"
    loopback loop $isofile
    linux  (loop)/images/pxeboot/vmlinuz root=live:CDLABEL=NOBARA_ISO_CDLABEL rd.live.image nomodeset inst.ks=hd:LABEL=Ventoy:/kickstart/nobara-theme-bash.ks
    initrd (loop)/images/pxeboot/initrd.img
}

menuentry "Nobara -- [h] Headless vLLM      (kein GUI, Podman + vLLM als Dienst)" --hotkey=h {
    search --no-floppy --label --set=root Ventoy
    set isofile="/NOBARA_ISO_FILENAME"
    loopback loop $isofile
    linux  (loop)/images/pxeboot/vmlinuz root=live:CDLABEL=NOBARA_ISO_CDLABEL rd.live.image inst.ks=hd:LABEL=Ventoy:/kickstart/nobara-headless-vllm.ks
    initrd (loop)/images/pxeboot/initrd.img
}

menuentry "Nobara -- [v] vLLM only          (kein GUI, kein Podman, Python venv)" --hotkey=v {
    search --no-floppy --label --set=root Ventoy
    set isofile="/NOBARA_ISO_FILENAME"
    loopback loop $isofile
    linux  (loop)/images/pxeboot/vmlinuz root=live:CDLABEL=NOBARA_ISO_CDLABEL rd.live.image inst.ks=hd:LABEL=Ventoy:/kickstart/nobara-vllm-only.ks
    initrd (loop)/images/pxeboot/initrd.img
}
