#version=RHEL9
# Fedora Linux — Unattended Installation
# Generated by fedora-install/lib/xml2ks.py
# !! Do not edit by hand — regenerate from XML config !!

text
poweroff

# ── Locale / keyboard / timezone ─────────────────────────────────────────────
keyboard --xlayouts='de'
lang de_DE.UTF-8
timezone Europe/Berlin --utc

# ── Network ───────────────────────────────────────────────────────────────────
network --bootproto=dhcp --device=link --activate
network --hostname=fedora-workstation

# ── Disk / partitioning ───────────────────────────────────────────────────────
# Mindest-Diskgröße: 80 GB (squashfs unkomprimiert ~22 GB + Reserve)
ignoredisk --only-use=vda
zerombr
clearpart --all --initlabel --drives=vda
bootloader --boot-drive=vda

# Btrfs mit @ / @home Subvolumes — Timeshift-kompatibel
# Swap entfällt: zram-generator übernimmt Swap im RAM
part /boot/efi --fstype=efi    --size=600  --ondrive=vda
part /boot     --fstype=xfs    --size=1024 --ondrive=vda
part btrfs.01  --fstype=btrfs  --size=1    --grow --ondrive=vda

btrfs none  --label=fedora --data=single --metadata=single  btrfs.01
btrfs /     --subvol --name=@      LABEL=fedora
btrfs /home --subvol --name=@home  LABEL=fedora

# ── Bootloader ────────────────────────────────────────────────────────────────
# (bootloader directive oben — vor part — sonst "Kickstart nicht ausreichend")

# ── Authentication ────────────────────────────────────────────────────────────
rootpw --lock
user --groups=wheel,libvirt,video,audio --name=sija --password=$6$44c989d29609f973$7QBIfg7sNEWDBZjMc9zqD57buujYlXEBwSNnXFTIQz6lZJiEVQ25T9Nsw76HIRiKeiPHOwhdg2FAQVXa18gMA1  --iscrypted

# ── Services ──────────────────────────────────────────────────────────────────
services --enabled=sshd

# ── Packages ──────────────────────────────────────────────────────────────────
%packages --ignoremissing --retries=10
@^workstation-product-environment
git
curl
python3
python3-pip
python3-virtualenv
gnome-shell-extension-user-theme
gnome-shell-extension-dash-to-panel
flatpak
make
gcc
gcc-c++
cmake
ninja-build
openssh-server
virt-manager
qemu-kvm
libvirt
zenity
%end

# ── %addon kdump ──────────────────────────────────────────────────────────────

# ── %post: install first-boot service and first-login runner ──────────────────
%post --log=/root/ks-post.log

set -euo pipefail

# ── Write provisioning environment ───────────────────────────────────────────
cat > /etc/fedora-provision.env <<'ENVEOF'
FEDORA_TARGET_USER="sija"
FEDORA_PYTORCH_VENV="~/.venvs/ai"
FEDORA_VLLM_VENV="~/.venvs/bitwig-omni"
FEDORA_AUDIO_VENV="~/.venvs/kimi-audio"
FEDORA_VLLM_CUDA_VERSION="13.0"
FEDORA_VLLM_ARCH_LIST="12.0"
FEDORA_AUDIO_MODEL="moonshotai/Kimi-Audio-7B-Instruct"
FEDORA_AGENT_MODEL="Qwen/Qwen3-14B-AWQ"
FEDORA_NEO4J_URI="bolt://localhost:7687"
FEDORA_NEO4J_USER="neo4j"
FEDORA_NEO4J_PASSWORD="bitwig-agent"
FEDORA_WS_GTK_ARGS="-l -c Dark"
FEDORA_WS_ICON_ARGS=""
FEDORA_WS_WALL_ARGS=""
FEDORA_OMB_THEME="modern"
ENVEOF
chmod 0644 /etc/fedora-provision.env

# ── Btrfs mount options: compress + noatime ───────────────────────────────────
if grep -q 'btrfs' /etc/fstab 2>/dev/null; then
    sed -i '/\sbtrfs\s/ s/defaults/defaults,compress=zstd:1,noatime/' /etc/fstab
fi

# ── Passwordless sudo für Test-VM (kein interaktives Passwort via SSH) ────────
echo 'sija ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/99-sija-nopasswd
chmod 0440 /etc/sudoers.d/99-sija-nopasswd

# ── GDM Autologin ─────────────────────────────────────────────────────────────
cat > /etc/gdm/custom.conf <<'GDMEOF'
[daemon]
AutomaticLoginEnable=True
AutomaticLogin=sija
GDMEOF

# ── Write first-boot script ───────────────────────────────────────────────────
cat > /usr/local/sbin/fedora-first-boot.sh <<'FBEOF'
#!/usr/bin/env bash
# scripts/first-boot.sh — System-wide one-shot provisioning (runs as root via systemd)
#
# Executed by fedora-first-boot.service exactly once after the first boot.
# Marker: /var/lib/fedora-provision/first-boot.done
#
# Tasks:
#   1. System-Update (dnf upgrade)
#   2. NVIDIA Open Driver update
#   3. CUDA installation (Fedora/Fedora or NVIDIA repo)
#   4. Set system-wide CUDA environment variables

set -euo pipefail

MARKER_DIR="/var/lib/fedora-provision"
MARKER_FILE="$MARKER_DIR/first-boot.done"
LOG_FILE="/var/log/fedora-first-boot.log"
ENV_FILE="/etc/fedora-provision.env"
CUDA_ENV_FILE="/etc/profile.d/cuda.sh"

exec > >(tee -a "$LOG_FILE") 2>&1

log()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO]  $*"; }
warn() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [WARN]  $*"; }
err()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] $*" >&2; }
die()  { err "$*"; exit 1; }
step() { echo; echo "══ $* ══"; }

# ── Idempotency guard ─────────────────────────────────────────────────────────
if [[ -f "$MARKER_FILE" ]]; then
    log "First-boot already completed (marker exists: $MARKER_FILE). Skipping."
    exit 0
fi

mkdir -p "$MARKER_DIR"

# ── Load provisioning env ─────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$ENV_FILE"
fi

# ── 1. System-Update ──────────────────────────────────────────────────────────
step "System-Update"
log "Running dnf upgrade..."
dnf upgrade -y || die "dnf upgrade failed."
log "dnf upgrade completed."

# ── 2. NVIDIA Open Driver ─────────────────────────────────────────────────────
step "NVIDIA Open Driver update"

check_nvidia_open_compat() {
    # Check GPU PCI IDs against architectures that support the Open Module:
    # Turing (TU1xx), Ampere (GA1xx), Ada Lovelace (AD1xx), Blackwell (GB1xx)
    if ! command -v lspci &>/dev/null; then
        warn "lspci not available; skipping GPU compatibility check."
        return 0
    fi
    local gpu_info
    gpu_info=$(lspci -nn | grep -i 'NVIDIA' || true)
    if [[ -z "$gpu_info" ]]; then
        warn "No NVIDIA GPU detected (VM or non-NVIDIA system) — skipping NVIDIA driver."
        return 1
    fi
    # Turing and later are supported; check for pre-Turing (GTX 10xx / Pascal GP1xx)
    if echo "$gpu_info" | grep -qiE 'GP10[0-9]|GP1[0-9]{2}'; then
        die "NVIDIA Pascal GPU detected. Open Driver requires Turing or newer. Aborting."
    fi
    log "NVIDIA GPU detected (Open Driver compatible): $gpu_info"
}

if check_nvidia_open_compat; then
    log "Installing/updating NVIDIA Open Kernel Module driver..."
    dnf install -y  kernel  kernel-devel  kernel-headers  akmod-nvidia-open  xorg-x11-drv-nvidia-cuda  || die "NVIDIA Open Driver installation failed. No proprietary fallback."

    # Wait for the kmod to be built (akmods)
    if command -v akmods &>/dev/null; then
        log "Building kernel modules (akmods)..."
        akmods --force || die "akmods failed for NVIDIA Open Driver."
    fi
    log "NVIDIA Open Driver installed/updated."
fi

# ── 3. CUDA installation ──────────────────────────────────────────────────────
step "CUDA installation"

if ! lspci -nn 2>/dev/null | grep -qi 'NVIDIA'; then
    log "No NVIDIA GPU — skipping CUDA installation."
else

CUDA_SOURCE="${FEDORA_CUDA_SOURCE:-nvidia}"

install_cuda_fedora() {
    log "Installing CUDA from Fedora/Fedora repos..."
    dnf install -y  cuda  cuda-toolkit  cuda-devel  || die "CUDA installation from Fedora/Fedora repos failed."
}

install_cuda_nvidia_repo() {
    log "Installing CUDA from official NVIDIA repo..."
    local arch; arch=$(uname -m)
    local distro="rhel9"
    local repo_url="https://developer.download.nvidia.com/compute/cuda/repos/${distro}/${arch}/cuda-${distro}.repo"

    if ! dnf config-manager --add-repo "$repo_url" 2>/dev/null; then
        # Try with dnf5 syntax
        dnf config-manager addrepo --from-repofile="$repo_url"  || die "Failed to add NVIDIA CUDA repo."
    fi

    dnf install -y  cuda-toolkit  cuda-devel  || die "CUDA installation from NVIDIA repo failed."
}

case "$CUDA_SOURCE" in
    fedora) install_cuda_fedora   ;;
    nvidia)        install_cuda_nvidia_repo ;;
    *)             die "Unknown cuda source: $CUDA_SOURCE" ;;
esac

fi  # end: NVIDIA GPU check

# Discover installed CUDA path and write env (only if GPU present)
if lspci -nn 2>/dev/null | grep -qi 'NVIDIA'; then

CUDA_HOME_DETECTED=""
for candidate in /usr/local/cuda /usr/local/cuda-*; do
    if [[ -x "${candidate}/bin/nvcc" ]]; then
        CUDA_HOME_DETECTED="$candidate"
        break
    fi
done
[[ -n "$CUDA_HOME_DETECTED" ]] || die "nvcc not found after CUDA installation."
log "CUDA installed at: $CUDA_HOME_DETECTED"

CUDA_VERSION_INSTALLED=$("${CUDA_HOME_DETECTED}/bin/nvcc" --version  | grep -oP 'release \K[\d.]+' | head -1)
log "CUDA version: $CUDA_VERSION_INSTALLED"

# ── 4. System-wide CUDA environment variables ─────────────────────────────────
step "CUDA environment variables"

cat > "$CUDA_ENV_FILE" <<ENVEOF
# Fedora Auto-Install: CUDA environment — managed by fedora-first-boot.sh
export CUDA_HOME="${CUDA_HOME_DETECTED}"
export PATH="\${CUDA_HOME}/bin\${PATH:+:\$PATH}"
export LD_LIBRARY_PATH="\${CUDA_HOME}/lib64\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
ENVEOF
chmod 0644 "$CUDA_ENV_FILE"
log "CUDA env written to $CUDA_ENV_FILE"

# Also write a systemd-compatible EnvironmentFile entry
mkdir -p /etc/systemd/system.conf.d
cat > /etc/systemd/system.conf.d/cuda-env.conf <<SYSENVEOF
# CUDA environment for systemd services
[Manager]
DefaultEnvironment=CUDA_HOME=${CUDA_HOME_DETECTED}
SYSENVEOF
systemctl daemon-reload

fi  # end: CUDA env setup

# ── 5. GDM Autologin ──────────────────────────────────────────────────────────
step "GDM Autologin setup"
# Add autologin to daemon section
if grep -q 'AutomaticLoginEnable' /etc/gdm/custom.conf; then
    log "GDM autologin already configured."
else
    sed -i '/^\[daemon\]/a AutomaticLoginEnable=true' /etc/gdm/custom.conf
    sed -i '/AutomaticLoginEnable=true/a AutomaticLogin=sija' /etc/gdm/custom.conf
fi
log "GDM autologin configured."

# ── Done ──────────────────────────────────────────────────────────────────────
step "First-boot provisioning complete"
marker_set() { mkdir -p "$(dirname "$1")"; touch "$1"; }
marker_set "$MARKER_FILE"
log "Marker written: $MARKER_FILE"
log "First-boot provisioning finished successfully."

FBEOF
chmod 0750 /usr/local/sbin/fedora-first-boot.sh

# ── Write first-login runner ──────────────────────────────────────────────────
cat > /usr/local/bin/fedora-first-login.sh <<'FLEOF'
#!/usr/bin/env bash
# scripts/first-login.sh — User-level one-shot provisioning for the target user
#
# Runs via ~/.config/autostart/fedora-first-login.desktop on first GNOME login.
# Marker: ~/.local/share/fedora-provision/first-login.done
#
# Tasks (in order):
#   1.  Flatpak Extension Manager
#   2.  Enable GNOME extensions
#   3.  WhiteSur GTK theme  (git clone / pull + install)
#   4.  WhiteSur Icon theme
#   5.  WhiteSur Wallpapers
#   6.  Oh My Bash (install + set theme)
#   7.  Python venv ~/.venvs/ai
#   8.  CUDA compat check → PyTorch install
#   9.  vLLM-Omni venv + HuggingFace CLI
#   10. CUDA 13.0 toolchain check/install
#   11. vLLM PyPI wheel / source build (sm120 / CUDA 13.0)
#   12. Download Kimi-Audio-7B-Instruct (audio analysis model)
#   13. Download Qwen3-14B-AWQ (Bitwig agent model)
#   14. Neo4j driver + Bitwig agent scaffold

set -euo pipefail

MARKER_DIR="${HOME}/.local/share/fedora-provision"
MARKER_FILE="${MARKER_DIR}/first-login.done"
LOG_FILE="${MARKER_DIR}/first-login.log"
ENV_FILE="/etc/fedora-provision.env"

mkdir -p "$MARKER_DIR"
exec > >(tee -a "$LOG_FILE") 2>&1

log()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO]  $*"; }
warn() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [WARN]  $*"; }
err()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] $*" >&2; }
die()  { err "$*"; exit 1; }
step() { echo; echo "══ $* ══"; }

have_passwordless_sudo() {
    sudo -n true 2>/dev/null
}

# ── Idempotency guard ─────────────────────────────────────────────────────────
if [[ -f "$MARKER_FILE" ]]; then
    log "First-login already completed. Removing autostart entry."
    rm -f "${HOME}/.config/autostart/fedora-first-login.desktop"
    exit 0
fi

# ── Load provisioning env ─────────────────────────────────────────────────────
[[ -f "$ENV_FILE" ]] && source "$ENV_FILE"

TARGET_USER="${FEDORA_TARGET_USER:-${USER}}"
PYTORCH_VENV="${FEDORA_PYTORCH_VENV:-${HOME}/.venvs/ai}"
VLLM_VENV="${FEDORA_VLLM_VENV:-${HOME}/.venvs/bitwig-omni}"
VLLM_CUDA_VERSION="${FEDORA_VLLM_CUDA_VERSION:-13.2}"
VLLM_ARCH_LIST="${FEDORA_VLLM_ARCH_LIST:-12.0}"
VLLM_MODEL="${FEDORA_VLLM_MODEL:-Qwen/Qwen3-14B-AWQ}"
WS_GTK_ARGS="${FEDORA_WS_GTK_ARGS:-}"
WS_ICON_ARGS="${FEDORA_WS_ICON_ARGS:-}"
WS_WALL_ARGS="${FEDORA_WS_WALL_ARGS:-}"
OMB_THEME="${FEDORA_OMB_THEME:-modern}"

THEMES_DIR="${HOME}/themes"

# ── 1. Flatpak Extension Manager ──────────────────────────────────────────────
step "Flatpak Extension Manager"
if ! flatpak list --user 2>/dev/null | grep -q 'com.mattjakeman.ExtensionManager'; then
    log "Installing Extension Manager..."
    flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager  || warn "Extension Manager install failed (non-fatal)."
else
    log "Extension Manager already installed."
fi

# ── 2. Enable GNOME extensions ────────────────────────────────────────────────
step "GNOME extensions"
if command -v gnome-extensions &>/dev/null; then
    for ext in  "user-theme@gnome-shell-extensions.gcampax.github.com"  "dash-to-panel@jderose9.github.com"; do
        if gnome-extensions list 2>/dev/null | grep -qF "$ext"; then
            gnome-extensions enable "$ext" 2>/dev/null  && log "Enabled: $ext"  || warn "Could not enable: $ext"
        else
            warn "Extension not installed (did Kickstart %post run?): $ext"
        fi
    done
else
    warn "gnome-extensions CLI not found; skipping."
fi

# ── 3-5. WhiteSur themes ──────────────────────────────────────────────────────
step "WhiteSur themes"

WHITESUR_ERRORS=()

ws_install_theme() {
    local repo_name="$1"       # e.g. WhiteSur-gtk-theme
    local repo_url="$2"
    local install_dest_flag="$3"   # e.g. "-d ~/.local/share/themes"
    local extra_args="$4"
    local install_dir="${THEMES_DIR}/${repo_name}"

    log "WhiteSur: $repo_name"

    # Clone or pull
    if [[ -d "$install_dir/.git" ]]; then
        log "  Updating existing repo..."
        git -C "$install_dir" pull --ff-only 2>&1 | while read -r l; do log "  git: $l"; done ||  warn "  git pull failed for $repo_name (continuing)."
    else
        mkdir -p "$THEMES_DIR"
        log "  Cloning $repo_url..."
        git clone --depth=1 "$repo_url" "$install_dir" 2>&1 |  while read -r l; do log "  git: $l"; done || {
                WHITESUR_ERRORS+=("$repo_name: git clone failed")
                return
            }
    fi

    # Determine install arguments — skip interactive prompt (run with defaults if empty)
    local args_var="$extra_args"

    # Run installer
    local install_sh="${install_dir}/install.sh"
    if [[ ! -x "$install_sh" ]]; then
        WHITESUR_ERRORS+=("$repo_name: install.sh not found or not executable")
        return
    fi

    # shellcheck disable=SC2086
    # TERM=xterm: setterm inside install.sh fails with TERM=dumb/unset (no TTY in %post), exiting non-zero
    local _tmpout
    _tmpout=$(mktemp)
    if TERM=xterm bash "$install_sh" $install_dest_flag $args_var >"$_tmpout" 2>&1; then
        while IFS= read -r l; do log "  install: $l"; done < "$_tmpout"
        rm -f "$_tmpout"
        log "  $repo_name installed successfully."
    else
        while IFS= read -r l; do log "  install: $l"; done < "$_tmpout"
        rm -f "$_tmpout"
        WHITESUR_ERRORS+=("$repo_name: install.sh exited with error")
    fi
}

GTK_DEST="-d ${HOME}/.local/share/themes"
ICON_DEST="-d ${HOME}/.local/share/icons"

ws_install_theme  "WhiteSur-gtk-theme"  "https://github.com/vinceliuice/WhiteSur-gtk-theme.git"  "$GTK_DEST"  "$WS_GTK_ARGS"

ws_install_theme  "WhiteSur-icon-theme"  "https://github.com/vinceliuice/WhiteSur-icon-theme.git"  "$ICON_DEST"  "$WS_ICON_ARGS"

ws_install_theme  "WhiteSur-wallpapers"  "https://github.com/vinceliuice/WhiteSur-wallpapers.git"  ""  "$WS_WALL_ARGS"

# ── 6. Oh My Bash ─────────────────────────────────────────────────────────────
step "Oh My Bash"

OMB_DIR="${HOME}/.oh-my-bash"
if [[ -d "$OMB_DIR" ]]; then
    log "Oh My Bash already installed."
else
    log "Installing Oh My Bash (unattended)..."
    bash <(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)  --unattended  || warn "Oh My Bash install script failed (non-fatal)."
fi

# Set / correct theme in ~/.bashrc
if [[ -f "${HOME}/.bashrc" ]]; then
    if grep -q 'OSH_THEME=' "${HOME}/.bashrc"; then
        sed -i "s|^OSH_THEME=.*|OSH_THEME=\"${OMB_THEME}\"|" "${HOME}/.bashrc"
        log "Updated OSH_THEME to '${OMB_THEME}' in ~/.bashrc"
    else
        echo "OSH_THEME=\"${OMB_THEME}\"" >> "${HOME}/.bashrc"
        log "Appended OSH_THEME='${OMB_THEME}' to ~/.bashrc"
    fi
    # shellcheck source=/dev/null
    source "${HOME}/.bashrc" 2>/dev/null || true
fi

# ── 7. Python venv ~/.venvs/ai ────────────────────────────────────────────────
step "Python AI venv"

VENV_AI="${PYTORCH_VENV/#\~/$HOME}"
if [[ -d "$VENV_AI" ]]; then
    log "venv already exists: $VENV_AI"
else
    log "Creating venv: $VENV_AI"
    mkdir -p "$(dirname "$VENV_AI")"
    python3 -m venv "$VENV_AI"
fi

# Upgrade pip in venv
"$VENV_AI/bin/pip" install --quiet --upgrade pip

# ── 8. CUDA compatibility → PyTorch ───────────────────────────────────────────
step "PyTorch installation"

detect_cuda_version() {
    local nvcc_path
    for p in /usr/bin/nvcc /usr/local/cuda/bin/nvcc; do
        [[ -x "$p" ]] && { "$p" --version | grep -oP 'release \K[\d.]+' | head -1; return; }
    done
    echo ""
}

resolve_pytorch_index() {
    local cuda_ver="$1"
    local major minor
    major=$(echo "$cuda_ver" | cut -d. -f1)
    minor=$(echo "$cuda_ver" | cut -d. -f2)
    local ver_int=$(( major * 100 + minor ))

    # Map CUDA version → PyTorch wheel index
    # Prefer the highest known cu-tag that is <= installed CUDA
    if   (( ver_int >= 1300 )); then echo "https://download.pytorch.org/whl/cu130"
    elif (( ver_int >= 1206 )); then echo "https://download.pytorch.org/whl/cu126"
    elif (( ver_int >= 1204 )); then echo "https://download.pytorch.org/whl/cu124"
    elif (( ver_int >= 1201 )); then echo "https://download.pytorch.org/whl/cu121"
    elif (( ver_int >= 1200 )); then echo "https://download.pytorch.org/whl/cu118"
    else  echo "https://download.pytorch.org/whl/cpu"
    fi
}

CUDA_VER=$(detect_cuda_version)
if [[ -z "$CUDA_VER" ]]; then
    warn "CUDA not detected; installing CPU-only PyTorch."
    PYTORCH_INDEX="https://download.pytorch.org/whl/cpu"
else
    log "Detected CUDA $CUDA_VER"
    PYTORCH_INDEX=$(resolve_pytorch_index "$CUDA_VER")
fi
log "PyTorch index: $PYTORCH_INDEX"

"$VENV_AI/bin/pip" install --quiet  torch torchvision torchaudio  --index-url "$PYTORCH_INDEX"

log "Verifying PyTorch..."
"$VENV_AI/bin/python3" -c "
import torch
print(f'  PyTorch {torch.__version__}')
print(f'  CUDA available: {torch.cuda.is_available()}')
if torch.cuda.is_available():
    print(f'  CUDA version: {torch.version.cuda}')
    print(f'  GPU: {torch.cuda.get_device_name(0)}')
" || warn "PyTorch verification script failed (non-fatal)."

# ── 9. vLLM-Omni venv + HuggingFace CLI ──────────────────────────────────────
step "vLLM-Omni venv"

VENV_VLLM="${VLLM_VENV/#\~/$HOME}"
if [[ -d "$VENV_VLLM" ]]; then
    log "vLLM-Omni venv already exists: $VENV_VLLM"
else
    log "Creating vLLM-Omni venv: $VENV_VLLM"
    mkdir -p "$(dirname "$VENV_VLLM")"
    python3 -m venv "$VENV_VLLM"
fi

"$VENV_VLLM/bin/pip" install --quiet --upgrade pip

log "Installing HuggingFace CLI + autoawq in vLLM-Omni venv..."
"$VENV_VLLM/bin/pip" install --quiet  "huggingface_hub[cli]"  autoawq  || warn "HuggingFace CLI / autoawq install failed (non-fatal)."

log "HuggingFace CLI installed. Token will be prompted lazily on first download."

# ── 10. CUDA 13.0 toolchain for vLLM / Bitwig agent ─────────────────────────
step "CUDA ${VLLM_CUDA_VERSION} toolchain"

find_cuda_version_path() {
    local target_ver="$1"
    # Check /usr/local/cuda-X.Y symlink/dir
    for p in "/usr/local/cuda-${target_ver}" "/usr/local/cuda"; do
        if [[ -x "${p}/bin/nvcc" ]]; then
            local found_ver
            found_ver=$("${p}/bin/nvcc" --version | grep -oP 'release \K[\d.]+' | head -1)
            if [[ "$found_ver" == "$target_ver"* ]]; then
                echo "$p"
                return 0
            fi
        fi
    done
    return 1
}

CUDA_132_PATH=""
if CUDA_132_PATH=$(find_cuda_version_path "$VLLM_CUDA_VERSION"); then
    log "CUDA ${VLLM_CUDA_VERSION} found at: $CUDA_132_PATH"
else
    log "CUDA ${VLLM_CUDA_VERSION} not found. Attempting installation..."

    # Try dnf first (Fedora/Fedora may have it)
    CUDA_MAJOR=$(echo "$VLLM_CUDA_VERSION" | cut -d. -f1)
    CUDA_MINOR=$(echo "$VLLM_CUDA_VERSION" | cut -d. -f2)
    CUDA_PKG="cuda-toolkit-${CUDA_MAJOR}-${CUDA_MINOR}"

    if have_passwordless_sudo && sudo dnf install -y "$CUDA_PKG" 2>/dev/null; then
        log "Installed $CUDA_PKG via dnf."
    else
        if ! have_passwordless_sudo; then
            die "CUDA ${VLLM_CUDA_VERSION} is missing and passwordless sudo is not available in first-login context. Install CUDA ${VLLM_CUDA_VERSION} manually or via first-boot, then re-run."
        fi
        # Fall back to NVIDIA runfile installer (side-by-side, no system CUDA overwrite)
        log "dnf package not available. Downloading NVIDIA CUDA ${VLLM_CUDA_VERSION} runfile..."
        RUNFILE_URL="https://developer.download.nvidia.com/compute/cuda/${VLLM_CUDA_VERSION}/local_installers/cuda_${VLLM_CUDA_VERSION}_linux.run"
        RUNFILE="/tmp/cuda-${VLLM_CUDA_VERSION}-installer.run"

        curl -L --retry 5 --progress-bar -o "$RUNFILE" "$RUNFILE_URL"  || die "Failed to download CUDA ${VLLM_CUDA_VERSION} runfile from NVIDIA."

        chmod +x "$RUNFILE"
        sudo "$RUNFILE"  --silent  --toolkit  --toolkitpath="/usr/local/cuda-${VLLM_CUDA_VERSION}"  --no-opengl-libs  --override  || die "CUDA ${VLLM_CUDA_VERSION} runfile installation failed."

        rm -f "$RUNFILE"
        log "CUDA ${VLLM_CUDA_VERSION} installed to /usr/local/cuda-${VLLM_CUDA_VERSION}"
    fi

    CUDA_132_PATH=$(find_cuda_version_path "$VLLM_CUDA_VERSION")  || die "CUDA ${VLLM_CUDA_VERSION} still not found after installation."
fi

# Write venv activation hook to set CUDA 13.0 env for this venv
VENV_ACTIVATE_HOOK="${VENV_VLLM}/bin/activate.d"
mkdir -p "$VENV_ACTIVATE_HOOK"
cat > "${VENV_VLLM}/bin/activate.cuda" <<HOOKEOF
# Auto-sourced for vLLM-Omni venv — sets CUDA ${VLLM_CUDA_VERSION} paths
export CUDA_HOME="${CUDA_132_PATH}"
export PATH="\${CUDA_HOME}/bin\${PATH:+:\$PATH}"
export LD_LIBRARY_PATH="\${CUDA_HOME}/lib64\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
HOOKEOF

# Inject into venv's activate script
if ! grep -q 'activate.cuda' "${VENV_VLLM}/bin/activate"; then
    echo '' >> "${VENV_VLLM}/bin/activate"
    echo '# Fedora: CUDA toolchain for vLLM-Omni' >> "${VENV_VLLM}/bin/activate"
    echo "source \"${VENV_VLLM}/bin/activate.cuda\"" >> "${VENV_VLLM}/bin/activate"
fi
log "CUDA ${VLLM_CUDA_VERSION} environment configured for venv: $VENV_VLLM"

# ── 11. vLLM-Omni source build ────────────────────────────────────────────────
step "vLLM-Omni source build (CUDA ${VLLM_CUDA_VERSION}, sm${VLLM_ARCH_LIST//./})"

VLLM_OMNI_SRC="${HOME}/.local/src/vllm-omni"

if [[ -d "${VLLM_OMNI_SRC}/.git" ]]; then
    log "vLLM-Omni source already cloned. Pulling latest..."
    git -C "$VLLM_OMNI_SRC" pull --ff-only || warn "git pull failed; using existing source."
else
    log "Cloning vLLM-Omni..."
    mkdir -p "$(dirname "$VLLM_OMNI_SRC")"
    git clone --depth=1 https://github.com/vllm-project/vllm.git "$VLLM_OMNI_SRC"  || die "Failed to clone vLLM-Omni."
fi

# Apply use_existing_torch.py to prevent overwriting the system PyTorch
if [[ -f "${VLLM_OMNI_SRC}/use_existing_torch.py" ]]; then
    log "Running use_existing_torch.py (protects external PyTorch installations)..."
    (cd "$VLLM_OMNI_SRC" && "$VENV_VLLM/bin/python3" use_existing_torch.py)  || warn "use_existing_torch.py failed (non-fatal, continuing build)."
fi

log "Building vLLM-Omni against CUDA ${VLLM_CUDA_VERSION} + sm${VLLM_ARCH_LIST//./}..."
(
    cd "$VLLM_OMNI_SRC"
    # Activate venv environment for build
    source "${VENV_VLLM}/bin/activate"
    source "${VENV_VLLM}/bin/activate.cuda"

    export TORCH_CUDA_ARCH_LIST="${VLLM_ARCH_LIST}"
    export CUDA_HOME="${CUDA_132_PATH}"
    export MAX_JOBS="${MAX_JOBS:-$(nproc)}"

    pip install --quiet --no-build-isolation .  || die "vLLM-Omni build failed."
)
log "vLLM-Omni build completed."

# ── 12. Download model ────────────────────────────────────────────────────────
step "Model download: ${VLLM_MODEL}"

log "Checking HuggingFace login..."
log "Downloading model: ${VLLM_MODEL} ..."
# Lazy token behavior: download will prompt for login only when required.
"$VENV_VLLM/bin/huggingface-cli" download "${VLLM_MODEL}"  --local-dir "${HOME}/.cache/huggingface/hub/${VLLM_MODEL//\//__}"  || warn "Model download failed or deferred (check HF token / disk space)."

# ── Final report ──────────────────────────────────────────────────────────────
step "First-login provisioning complete"

if [[ "${#WHITESUR_ERRORS[@]}" -gt 0 ]]; then
    warn "WhiteSur errors encountered:"
    for e in "${WHITESUR_ERRORS[@]}"; do
        warn "  - $e"
    done
fi

touch "$MARKER_FILE"
log "Marker written: $MARKER_FILE"

# Remove autostart entry — we're done
rm -f "${HOME}/.config/autostart/fedora-first-login.desktop"
log "Autostart entry removed."
log "First-login provisioning finished. Log: $LOG_FILE"

FLEOF
chmod 0755 /usr/local/bin/fedora-first-login.sh

# ── Write systemd unit for first-boot ────────────────────────────────────────
cat > /etc/systemd/system/fedora-first-boot.service <<'UNITEOF'
[Unit]
Description=Fedora First-Boot Provisioning (one-shot)
Documentation=https://github.com/user/fedora-install
After=network-online.target
Wants=network-online.target
# Ensure this runs only on first boot; marker file disables it on subsequent boots
ConditionPathExists=!/var/lib/fedora-provision/first-boot.done

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/fedora-first-boot.sh
EnvironmentFile=-/etc/fedora-provision.env
StandardOutput=journal+console
StandardError=journal+console
TimeoutStartSec=3600
RemainAfterExit=yes

# Prevent privilege escalation
NoNewPrivileges=no
# Service runs as root (required for dnf, systemctl, akmods)
User=root

[Install]
WantedBy=multi-user.target

UNITEOF

systemctl enable fedora-first-boot.service
systemctl set-default graphical.target
systemctl enable gdm.service

# ── Install Extension Manager (Flatpak) at system level ──────────────────────
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo 2>/dev/null || true

# ── Configure first-login autorun for target user ────────────────────────────
USER_HOME="/home/sija"
AUTOSTART_DIR="$USER_HOME/.config/autostart"
mkdir -p "$AUTOSTART_DIR"
cat > "$AUTOSTART_DIR/fedora-first-login.desktop" <<'DESKTOPEOF'
[Desktop Entry]
Type=Application
Name=Fedora First-Login Setup
Exec=/usr/local/bin/fedora-first-login.sh
Hidden=false
NoDisplay=true
X-GNOME-Autostart-enabled=true
DESKTOPEOF
chown -R sija:sija "$USER_HOME/.config"

%end

# ── %post --nochroot: Btrfs Subvolumes → @/@home umbenennen (Timeshift-kompatibel) ──
%post --nochroot --log=/root/ks-post-btrfs-rename.log

set -euo pipefail

SYSIMAGE="/mnt/sysimage"
BTRFS_DEV=$(findmnt -n -o SOURCE "${SYSIMAGE}" 2>/dev/null | sed 's/\[.*\]//' || true)

if [[ -z "$BTRFS_DEV" ]]; then
    echo "WARN: Kein btrfs Device erkannt — Subvolume-Rename übersprungen."
    exit 0
fi

MOUNT_TMP=$(mktemp -d)
mount -o subvolid=5 "$BTRFS_DEV" "$MOUNT_TMP"

# root → @ (Snapshot, dann fstab anpassen — root bleibt als Fallback erhalten)
if [[ -d "${MOUNT_TMP}/root" ]] && [[ ! -d "${MOUNT_TMP}/@" ]]; then
    btrfs subvolume snapshot "${MOUNT_TMP}/root" "${MOUNT_TMP}/@"
    echo "Subvolume Snapshot: root → @"
fi

# home → @home
if [[ -d "${MOUNT_TMP}/home" ]] && [[ ! -d "${MOUNT_TMP}/@home" ]]; then
    btrfs subvolume snapshot "${MOUNT_TMP}/home" "${MOUNT_TMP}/@home"
    echo "Subvolume Snapshot: home → @home"
fi

umount "$MOUNT_TMP"
rmdir "$MOUNT_TMP"

# fstab auf neue Subvolume-Namen aktualisieren
sed -i 's/subvol=root\b/subvol=@/g'      "${SYSIMAGE}/etc/fstab"
sed -i 's/subvol=home\b/subvol=@home/g'  "${SYSIMAGE}/etc/fstab"
echo "fstab aktualisiert: subvol=root → @, subvol=home → @home"

%end

# ── %post --nochroot: Provisioner + Scripts ins Zielsystem einbetten ──────────
%post --nochroot --log=/root/ks-post-embed-provisioner.log

set +e
SYSROOT="${ANA_INSTALL_PATH:-/mnt/sysroot}"
[[ ! -d "$SYSROOT" ]] && SYSROOT="/mnt/sysimage"
[[ ! -d "$SYSROOT" ]] && { echo "Kein sysroot gefunden — Abbruch."; exit 0; }

SRC=""
for candidate in /run/install/repo /run/install/sources/mount-* /mnt/install/repo; do
    if [[ -f "${candidate}/fedora-provision.sh" || -d "${candidate}/scripts" ]]; then
        SRC="$candidate"; break
    fi
done
if [[ -z "$SRC" ]]; then
    VENTOY_DEV=$(blkid -L Ventoy 2>/dev/null | head -1 || true)
    if [[ -n "$VENTOY_DEV" ]]; then
        MNT=$(mktemp -d)
        mount "$VENTOY_DEV" "$MNT" 2>/dev/null && SRC="$MNT"
    fi
fi
[[ -z "$SRC" ]] && { echo "Keine Quelle (ISO/USB) gefunden."; exit 0; }
echo "Quelle: $SRC"

mkdir -p "$SYSROOT/usr/local/sbin" \
         "$SYSROOT/usr/local/bin" \
         "$SYSROOT/usr/local/share/fedora-autoinstall" \
         "$SYSROOT/usr/share/applications"

[[ -f "${SRC}/fedora-provision.sh" ]] && \
    install -m 0750 "${SRC}/fedora-provision.sh" "$SYSROOT/usr/local/sbin/fedora-provision.sh"

[[ -f "${SRC}/scripts/welcome-dialog.sh" ]] && \
    install -m 0755 "${SRC}/scripts/welcome-dialog.sh" "$SYSROOT/usr/local/bin/fedora-welcome-dialog.sh"

[[ -f "${SRC}/scripts/fedora-provision.desktop" ]] && \
    install -m 0644 "${SRC}/scripts/fedora-provision.desktop" "$SYSROOT/usr/share/applications/fedora-provision.desktop"

[[ -d "${SRC}/scripts" ]]   && cp -r "${SRC}/scripts"   "$SYSROOT/usr/local/share/fedora-autoinstall/"
[[ -d "${SRC}/kickstart" ]] && cp -r "${SRC}/kickstart" "$SYSROOT/usr/local/share/fedora-autoinstall/"

echo "Provisioner + Scripts unter /usr/local/{sbin,bin,share}/ eingebettet."

%end

# ── %post: Welcome-Dialog Autostart (auch in VM zum Testen) ──────────────────
%post --log=/root/ks-post-welcome-autostart.log

TARGET_USER="sija"
USER_HOME="/home/${TARGET_USER}"

if id "$TARGET_USER" &>/dev/null; then
    AUTOSTART_DIR="${USER_HOME}/.config/autostart"
    mkdir -p "$AUTOSTART_DIR"
    cat > "${AUTOSTART_DIR}/fedora-welcome.desktop" <<DESKTOPEOF
[Desktop Entry]
Type=Application
Name=Fedora Welcome
Exec=/usr/local/bin/fedora-welcome-dialog.sh
Hidden=false
NoDisplay=true
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=8
DESKTOPEOF
    chown -R "${TARGET_USER}:${TARGET_USER}" "$AUTOSTART_DIR"
    echo "Welcome-Dialog Autostart für ${TARGET_USER} aktiviert."
fi

%end
