#version=RHEL9
# Fedora Linux — Unattended Installation
# Generated by fedora-install/lib/xml2ks.py
# !! Do not edit by hand — regenerate from XML config !!

text
reboot

# ── Locale / keyboard / timezone ─────────────────────────────────────────────
keyboard --xlayouts='de'
lang de_DE.UTF-8
timezone Europe/Berlin --utc

# ── Network ───────────────────────────────────────────────────────────────────
network --bootproto=dhcp --device=link --activate
network --hostname=fedora-workstation

# ── Disk / partitioning ───────────────────────────────────────────────────────
ignoredisk --only-use=sda
zerombr
clearpart --all --initlabel --drives=sda
autopart --type=lvm

# ── Bootloader ────────────────────────────────────────────────────────────────
bootloader --location=mbr --boot-drive=sda

# ── Authentication ────────────────────────────────────────────────────────────
rootpw --lock
user --groups=wheel,libvirt,video,audio --name=sija --password=$6$rounds=4096$exampleSalt$A2xI1.hfVf4M8bJH3uQ6Q7fKJ3QYgAnfYQPc0dyY8aTJiD9f8Lh3EEcKB6DzQ9s9lfhYf6Q2xv.YO1f4Yv4eY0 \
     --iscrypted --gecos="sija"

# ── Packages ──────────────────────────────────────────────────────────────────
%packages
@^fedora-desktop
git
curl
python3
python3-pip
python3-virtualenv
gnome-shell-extension-user-theme
gnome-shell-extension-dash-to-panel
flatpak
make
gcc
gcc-c++
cmake
ninja-build
git
curl
python3
python3-pip
python3-virtualenv
gnome-shell-extension-user-theme
gnome-shell-extension-dash-to-panel
flatpak
virt-manager
qemu-kvm
libvirt
%end

# ── %addon kdump ──────────────────────────────────────────────────────────────
%addon com_redhat_kdump --disable
%end

# ── %post: install first-boot service and first-login runner ──────────────────
%post --log=/root/ks-post.log

set -euo pipefail

# ── Write provisioning environment ───────────────────────────────────────────
cat > /etc/fedora-provision.env <<'ENVEOF'
FEDORA_TARGET_USER="sija"
FEDORA_VLLM_ROUTER_PORT="8000"
FEDORA_VLLM_REGISTRY="~/.config/vllm-router/models.json"
FEDORA_AGENT_MODEL="Qwen/Qwen3-14B-AWQ"
FEDORA_AUDIO_MODEL="moonshotai/Kimi-Audio-7B-Instruct"
FEDORA_WS_GTK_ARGS="-l -c Dark"
FEDORA_WS_ICON_ARGS="-dark"
FEDORA_WS_WALL_ARGS=""
FEDORA_OMB_THEME="modern"
ENVEOF
chmod 0644 /etc/fedora-provision.env

# ── Write first-boot script ───────────────────────────────────────────────────
cat > /usr/local/sbin/fedora-first-boot.sh <<'FBEOF'

FBEOF
chmod 0750 /usr/local/sbin/fedora-first-boot.sh

# ── Write first-login runner ──────────────────────────────────────────────────
cat > /usr/local/bin/fedora-first-login.sh <<'FLEOF'

FLEOF
chmod 0755 /usr/local/bin/fedora-first-login.sh

# ── Write systemd unit for first-boot ────────────────────────────────────────
cat > /etc/systemd/system/fedora-first-boot.service <<'UNITEOF'

UNITEOF

systemctl enable fedora-first-boot.service

# ── Install Extension Manager (Flatpak) at system level ──────────────────────
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo 2>/dev/null || true

# ── Configure first-login autorun for target user ────────────────────────────
USER_HOME="/home/sija"
AUTOSTART_DIR="$USER_HOME/.config/autostart"
mkdir -p "$AUTOSTART_DIR"
cat > "$AUTOSTART_DIR/fedora-first-login.desktop" <<'DESKTOPEOF'
[Desktop Entry]
Type=Application
Name=Fedora First-Login Setup
Exec=/usr/local/bin/fedora-first-login.sh
Hidden=false
NoDisplay=true
X-GNOME-Autostart-enabled=true
DESKTOPEOF
chown -R sija:sija "$AUTOSTART_DIR"

%end
