#version=RHEL9
# Nobara Linux — Unattended Installation
# Generated by nobara-install/lib/xml2ks.py
# !! Do not edit by hand — regenerate from XML config !!

text
reboot

# ── Locale / keyboard / timezone ─────────────────────────────────────────────
keyboard --xlayouts='de'
lang de_DE.UTF-8
timezone Europe/Berlin --utc

# ── Network ───────────────────────────────────────────────────────────────────
network --bootproto=dhcp --device=link --activate
network --hostname=nobara-workstation

# ── Disk / partitioning ───────────────────────────────────────────────────────
ignoredisk --only-use=vda
zerombr
clearpart --all --initlabel --drives=vda
autopart --type=lvm

# ── Bootloader ────────────────────────────────────────────────────────────────
bootloader --location=mbr --boot-drive=vda

# ── Authentication ────────────────────────────────────────────────────────────
rootpw --lock
user --groups=wheel,libvirt,video,audio --name=sija --password=$6$rounds=4096$exampleSalt$A2xI1.hfVf4M8bJH3uQ6Q7fKJ3QYgAnfYQPc0dyY8aTJiD9f8Lh3EEcKB6DzQ9s9lfhYf6Q2xv.YO1f4Yv4eY0 \
     --iscrypted --gecos="sija"

# ── Packages ──────────────────────────────────────────────────────────────────
%packages
@^nobara-desktop
git
curl
python3
python3-pip
python3-virtualenv
gnome-shell-extension-user-theme
gnome-shell-extension-dash-to-panel
flatpak
make
gcc
gcc-c++
cmake
ninja-build
git
curl
python3
python3-pip
python3-virtualenv
gnome-shell-extension-user-theme
gnome-shell-extension-dash-to-panel
flatpak
virt-manager
qemu-kvm
libvirt
%end

# ── %addon kdump ──────────────────────────────────────────────────────────────
%addon com_redhat_kdump --disable
%end

# ── %post: install first-boot service and first-login runner ──────────────────
%post --log=/root/ks-post.log

set -euo pipefail

# ── Write provisioning environment ───────────────────────────────────────────
cat > /etc/nobara-provision.env <<'ENVEOF'
NOBARA_TARGET_USER="sija"
NOBARA_PYTORCH_VENV="~/.venvs/ai"
NOBARA_VLLM_VENV="~/.venvs/bitwig-omni"
NOBARA_AUDIO_VENV="~/.venvs/kimi-audio"
NOBARA_VLLM_CUDA_VERSION="13.0"
NOBARA_VLLM_ARCH_LIST="12.0"
NOBARA_AUDIO_MODEL="moonshotai/Kimi-Audio-7B-Instruct"
NOBARA_AGENT_MODEL="Qwen/Qwen3-14B-AWQ"
NOBARA_NEO4J_URI="bolt://localhost:7687"
NOBARA_NEO4J_USER="neo4j"
NOBARA_NEO4J_PASSWORD="bitwig-agent"
NOBARA_WS_GTK_ARGS="-l -c Dark"
NOBARA_WS_ICON_ARGS="-dark"
NOBARA_WS_WALL_ARGS=""
NOBARA_OMB_THEME="modern"
ENVEOF
chmod 0644 /etc/nobara-provision.env

# ── Write first-boot script ───────────────────────────────────────────────────
cat > /usr/local/sbin/nobara-first-boot.sh <<'FBEOF'
#!/usr/bin/env bash
# scripts/first-boot.sh — System-wide one-shot provisioning (runs as root via systemd)
#
# Executed by nobara-first-boot.service exactly once after the first boot.
# Marker: /var/lib/nobara-provision/first-boot.done
#
# Tasks:
#   1. nobara-sync
#   2. NVIDIA Open Driver update
#   3. CUDA installation (Nobara/Fedora or NVIDIA repo)
#   4. Set system-wide CUDA environment variables

set -euo pipefail

MARKER_DIR="/var/lib/nobara-provision"
MARKER_FILE="$MARKER_DIR/first-boot.done"
LOG_FILE="/var/log/nobara-first-boot.log"
ENV_FILE="/etc/nobara-provision.env"
CUDA_ENV_FILE="/etc/profile.d/cuda.sh"

exec > >(tee -a "$LOG_FILE") 2>&1

log()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO]  $*"; }
warn() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [WARN]  $*"; }
err()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] $*" >&2; }
die()  { err "$*"; exit 1; }
step() { echo; echo "══ $* ══"; }

# ── Idempotency guard ─────────────────────────────────────────────────────────
if [[ -f "$MARKER_FILE" ]]; then
    log "First-boot already completed (marker exists: $MARKER_FILE). Skipping."
    exit 0
fi

mkdir -p "$MARKER_DIR"

# ── Load provisioning env ─────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$ENV_FILE"
fi

# ── 1. nobara-sync ────────────────────────────────────────────────────────────
step "nobara-sync"
if command -v nobara-sync &>/dev/null; then
    log "Running nobara-sync..."
    nobara-sync --headless || die "nobara-sync failed."
    log "nobara-sync completed."
else
    warn "nobara-sync not found; skipping."
fi

# ── 2. NVIDIA Open Driver ─────────────────────────────────────────────────────
step "NVIDIA Open Driver update"

check_nvidia_open_compat() {
    # Check GPU PCI IDs against architectures that support the Open Module:
    # Turing (TU1xx), Ampere (GA1xx), Ada Lovelace (AD1xx), Blackwell (GB1xx)
    if ! command -v lspci &>/dev/null; then
        warn "lspci not available; skipping GPU compatibility check."
        return 0
    fi
    local gpu_info
    gpu_info=$(lspci -nn | grep -i 'NVIDIA' || true)
    if [[ -z "$gpu_info" ]]; then
        die "No NVIDIA GPU detected. Cannot install NVIDIA Open Driver."
    fi
    # Turing and later are supported; check for pre-Turing (GTX 10xx / Pascal GP1xx)
    if echo "$gpu_info" | grep -qiE 'GP10[0-9]|GP1[0-9]{2}'; then
        die "NVIDIA Pascal GPU detected. Open Driver requires Turing or newer. Aborting."
    fi
    log "NVIDIA GPU detected (Open Driver compatible): $gpu_info"
}

check_nvidia_open_compat

log "Installing/updating NVIDIA Open Kernel Module driver..."
dnf install -y \
    kernel-devel \
    kernel-headers \
    akmod-nvidia-open \
    xorg-x11-drv-nvidia-cuda \
    || die "NVIDIA Open Driver installation failed. No proprietary fallback."

# Wait for the kmod to be built (akmods)
if command -v akmods &>/dev/null; then
    log "Building kernel modules (akmods)..."
    akmods --force || die "akmods failed for NVIDIA Open Driver."
fi
log "NVIDIA Open Driver installed/updated."

# ── 3. CUDA installation ──────────────────────────────────────────────────────
step "CUDA installation"

CUDA_SOURCE="${NOBARA_CUDA_SOURCE:-nobara}"

install_cuda_nobara() {
    log "Installing CUDA from Nobara/Fedora repos..."
    dnf install -y \
        cuda \
        cuda-toolkit \
        cuda-devel \
        || die "CUDA installation from Nobara/Fedora repos failed."
}

install_cuda_nvidia_repo() {
    log "Installing CUDA from official NVIDIA repo..."
    local arch; arch=$(uname -m)
    local distro="rhel9"
    local repo_url="https://developer.download.nvidia.com/compute/cuda/repos/${distro}/${arch}/cuda-${distro}.repo"

    if ! dnf config-manager --add-repo "$repo_url" 2>/dev/null; then
        # Try with dnf5 syntax
        dnf config-manager addrepo --from-repofile="$repo_url" \
            || die "Failed to add NVIDIA CUDA repo."
    fi

    dnf install -y \
        cuda-toolkit \
        cuda-devel \
        || die "CUDA installation from NVIDIA repo failed."
}

case "$CUDA_SOURCE" in
    nobara|fedora) install_cuda_nobara   ;;
    nvidia)        install_cuda_nvidia_repo ;;
    *)             die "Unknown cuda source: $CUDA_SOURCE" ;;
esac

# Discover installed CUDA path
CUDA_HOME_DETECTED=""
for candidate in /usr/local/cuda /usr/local/cuda-*; do
    if [[ -x "${candidate}/bin/nvcc" ]]; then
        CUDA_HOME_DETECTED="$candidate"
        break
    fi
done
[[ -n "$CUDA_HOME_DETECTED" ]] || die "nvcc not found after CUDA installation."
log "CUDA installed at: $CUDA_HOME_DETECTED"

CUDA_VERSION_INSTALLED=$("${CUDA_HOME_DETECTED}/bin/nvcc" --version \
    | grep -oP 'release \K[\d.]+' | head -1)
log "CUDA version: $CUDA_VERSION_INSTALLED"

# ── 4. System-wide CUDA environment variables ─────────────────────────────────
step "CUDA environment variables"

cat > "$CUDA_ENV_FILE" <<ENVEOF
# Nobara Auto-Install: CUDA environment — managed by nobara-first-boot.sh
export CUDA_HOME="${CUDA_HOME_DETECTED}"
export PATH="\${CUDA_HOME}/bin\${PATH:+:\$PATH}"
export LD_LIBRARY_PATH="\${CUDA_HOME}/lib64\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
ENVEOF
chmod 0644 "$CUDA_ENV_FILE"
log "CUDA env written to $CUDA_ENV_FILE"

# Also write a systemd-compatible EnvironmentFile entry
mkdir -p /etc/systemd/system.conf.d
cat > /etc/systemd/system.conf.d/cuda-env.conf <<SYSENVEOF
# CUDA environment for systemd services
[Manager]
DefaultEnvironment=CUDA_HOME=${CUDA_HOME_DETECTED}
SYSENVEOF
systemctl daemon-reload

# ── Done ──────────────────────────────────────────────────────────────────────
step "First-boot provisioning complete"
marker_set() { mkdir -p "$(dirname "$1")"; touch "$1"; }
marker_set "$MARKER_FILE"
log "Marker written: $MARKER_FILE"
log "First-boot provisioning finished successfully."

FBEOF
chmod 0750 /usr/local/sbin/nobara-first-boot.sh

# ── Write first-login runner ──────────────────────────────────────────────────
cat > /usr/local/bin/nobara-first-login.sh <<'FLEOF'
#!/usr/bin/env bash
# scripts/first-login.sh — User-level one-shot provisioning for the target user
#
# Runs via ~/.config/autostart/nobara-first-login.desktop on first GNOME login.
# Marker: ~/.local/share/nobara-provision/first-login.done
#
# Tasks (in order):
#   1.  Flatpak Extension Manager
#   2.  Enable GNOME extensions
#   3.  WhiteSur GTK theme  (git clone / pull + install)
#   4.  WhiteSur Icon theme
#   5.  WhiteSur Wallpapers
#   6.  Oh My Bash (install + set theme)
#   7.  Python venv ~/.venvs/ai
#   8.  CUDA compat check → PyTorch install
#   9.  vLLM-Omni venv + HuggingFace CLI
#   10. CUDA 13.0 toolchain check/install
#   11. vLLM PyPI wheel / source build (sm120 / CUDA 13.0)
#   12. Download Kimi-Audio-7B-Instruct (audio analysis model)
#   13. Download Qwen3-14B-AWQ (Bitwig agent model)
#   14. Neo4j driver + Bitwig agent scaffold

set -euo pipefail

MARKER_DIR="${HOME}/.local/share/nobara-provision"
MARKER_FILE="${MARKER_DIR}/first-login.done"
LOG_FILE="${MARKER_DIR}/first-login.log"
ENV_FILE="/etc/nobara-provision.env"

mkdir -p "$MARKER_DIR"
exec > >(tee -a "$LOG_FILE") 2>&1

log()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO]  $*"; }
warn() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [WARN]  $*"; }
err()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] $*" >&2; }
die()  { err "$*"; exit 1; }
step() { echo; echo "══ $* ══"; }

have_passwordless_sudo() {
    sudo -n true 2>/dev/null
}

# ── Idempotency guard ─────────────────────────────────────────────────────────
if [[ -f "$MARKER_FILE" ]]; then
    log "First-login already completed. Removing autostart entry."
    rm -f "${HOME}/.config/autostart/nobara-first-login.desktop"
    exit 0
fi

# ── Load provisioning env ─────────────────────────────────────────────────────
[[ -f "$ENV_FILE" ]] && source "$ENV_FILE"

TARGET_USER="${NOBARA_TARGET_USER:-${USER}}"
PYTORCH_VENV="${NOBARA_PYTORCH_VENV:-${HOME}/.venvs/ai}"
VLLM_VENV="${NOBARA_VLLM_VENV:-${HOME}/.venvs/bitwig-omni}"
VLLM_CUDA_VERSION="${NOBARA_VLLM_CUDA_VERSION:-13.2}"
VLLM_ARCH_LIST="${NOBARA_VLLM_ARCH_LIST:-12.0}"
VLLM_MODEL="${NOBARA_VLLM_MODEL:-Qwen/Qwen3-14B-AWQ}"
WS_GTK_ARGS="${NOBARA_WS_GTK_ARGS:-}"
WS_ICON_ARGS="${NOBARA_WS_ICON_ARGS:-}"
WS_WALL_ARGS="${NOBARA_WS_WALL_ARGS:-}"
OMB_THEME="${NOBARA_OMB_THEME:-modern}"

THEMES_DIR="${HOME}/themes"

# ── 1. Flatpak Extension Manager ──────────────────────────────────────────────
step "Flatpak Extension Manager"
if ! flatpak list --user 2>/dev/null | grep -q 'com.mattjakeman.ExtensionManager'; then
    log "Installing Extension Manager..."
    flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager \
        || warn "Extension Manager install failed (non-fatal)."
else
    log "Extension Manager already installed."
fi

# ── 2. Enable GNOME extensions ────────────────────────────────────────────────
step "GNOME extensions"
if command -v gnome-extensions &>/dev/null; then
    for ext in \
        "user-theme@gnome-shell-extensions.gcampax.github.com" \
        "dash-to-panel@jderose9.github.com"; do
        if gnome-extensions list 2>/dev/null | grep -qF "$ext"; then
            gnome-extensions enable "$ext" 2>/dev/null \
                && log "Enabled: $ext" \
                || warn "Could not enable: $ext"
        else
            warn "Extension not installed (did Kickstart %post run?): $ext"
        fi
    done
else
    warn "gnome-extensions CLI not found; skipping."
fi

# ── 3-5. WhiteSur themes ──────────────────────────────────────────────────────
step "WhiteSur themes"

WHITESUR_ERRORS=()

ws_install_theme() {
    local repo_name="$1"       # e.g. WhiteSur-gtk-theme
    local repo_url="$2"
    local install_dest_flag="$3"   # e.g. "-d ~/.local/share/themes"
    local extra_args="$4"
    local install_dir="${THEMES_DIR}/${repo_name}"

    log "WhiteSur: $repo_name"

    # Clone or pull
    if [[ -d "$install_dir/.git" ]]; then
        log "  Updating existing repo..."
        git -C "$install_dir" pull --ff-only 2>&1 | while read -r l; do log "  git: $l"; done || \
            warn "  git pull failed for $repo_name (continuing)."
    else
        mkdir -p "$THEMES_DIR"
        log "  Cloning $repo_url..."
        git clone --depth=1 "$repo_url" "$install_dir" 2>&1 | \
            while read -r l; do log "  git: $l"; done || {
                WHITESUR_ERRORS+=("$repo_name: git clone failed")
                return
            }
    fi

    # Determine install arguments
    local args_var="$extra_args"
    if [[ -z "$args_var" ]]; then
        read -r -p "  Enter install.sh args for ${repo_name} (Enter to skip): " args_var || true
    fi

    # Run installer
    local install_sh="${install_dir}/install.sh"
    if [[ ! -x "$install_sh" ]]; then
        WHITESUR_ERRORS+=("$repo_name: install.sh not found or not executable")
        return
    fi

    # shellcheck disable=SC2086
    if bash "$install_sh" $install_dest_flag $args_var 2>&1 | \
           while read -r l; do log "  install: $l"; done; then
        log "  $repo_name installed successfully."
    else
        WHITESUR_ERRORS+=("$repo_name: install.sh exited with error")
    fi
}

GTK_DEST="-d ${HOME}/.local/share/themes"
ICON_DEST="-d ${HOME}/.local/share/icons"

ws_install_theme \
    "WhiteSur-gtk-theme" \
    "https://github.com/vinceliuice/WhiteSur-gtk-theme.git" \
    "$GTK_DEST" \
    "$WS_GTK_ARGS"

ws_install_theme \
    "WhiteSur-icon-theme" \
    "https://github.com/vinceliuice/WhiteSur-icon-theme.git" \
    "$ICON_DEST" \
    "$WS_ICON_ARGS"

ws_install_theme \
    "WhiteSur-wallpapers" \
    "https://github.com/vinceliuice/WhiteSur-wallpapers.git" \
    "" \
    "$WS_WALL_ARGS"

# ── 6. Oh My Bash ─────────────────────────────────────────────────────────────
step "Oh My Bash"

OMB_DIR="${HOME}/.oh-my-bash"
if [[ -d "$OMB_DIR" ]]; then
    log "Oh My Bash already installed."
else
    log "Installing Oh My Bash (unattended)..."
    bash <(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh) \
        --unattended \
        || warn "Oh My Bash install script failed (non-fatal)."
fi

# Set / correct theme in ~/.bashrc
if [[ -f "${HOME}/.bashrc" ]]; then
    if grep -q 'OSH_THEME=' "${HOME}/.bashrc"; then
        sed -i "s|^OSH_THEME=.*|OSH_THEME=\"${OMB_THEME}\"|" "${HOME}/.bashrc"
        log "Updated OSH_THEME to '${OMB_THEME}' in ~/.bashrc"
    else
        echo "OSH_THEME=\"${OMB_THEME}\"" >> "${HOME}/.bashrc"
        log "Appended OSH_THEME='${OMB_THEME}' to ~/.bashrc"
    fi
    # shellcheck source=/dev/null
    source "${HOME}/.bashrc" 2>/dev/null || true
fi

# ── 7. Python venv ~/.venvs/ai ────────────────────────────────────────────────
step "Python AI venv"

VENV_AI="${PYTORCH_VENV/#\~/$HOME}"
if [[ -d "$VENV_AI" ]]; then
    log "venv already exists: $VENV_AI"
else
    log "Creating venv: $VENV_AI"
    mkdir -p "$(dirname "$VENV_AI")"
    python3 -m venv "$VENV_AI"
fi

# Upgrade pip in venv
"$VENV_AI/bin/pip" install --quiet --upgrade pip

# ── 8. CUDA compatibility → PyTorch ───────────────────────────────────────────
step "PyTorch installation"

detect_cuda_version() {
    local nvcc_path
    for p in /usr/bin/nvcc /usr/local/cuda/bin/nvcc; do
        [[ -x "$p" ]] && { "$p" --version | grep -oP 'release \K[\d.]+' | head -1; return; }
    done
    echo ""
}

resolve_pytorch_index() {
    local cuda_ver="$1"
    local major minor
    major=$(echo "$cuda_ver" | cut -d. -f1)
    minor=$(echo "$cuda_ver" | cut -d. -f2)
    local ver_int=$(( major * 100 + minor ))

    # Map CUDA version → PyTorch wheel index
    # Prefer the highest known cu-tag that is <= installed CUDA
    if   (( ver_int >= 1300 )); then echo "https://download.pytorch.org/whl/cu130"
    elif (( ver_int >= 1206 )); then echo "https://download.pytorch.org/whl/cu126"
    elif (( ver_int >= 1204 )); then echo "https://download.pytorch.org/whl/cu124"
    elif (( ver_int >= 1201 )); then echo "https://download.pytorch.org/whl/cu121"
    elif (( ver_int >= 1200 )); then echo "https://download.pytorch.org/whl/cu118"
    else  echo "https://download.pytorch.org/whl/cpu"
    fi
}

CUDA_VER=$(detect_cuda_version)
if [[ -z "$CUDA_VER" ]]; then
    warn "CUDA not detected; installing CPU-only PyTorch."
    PYTORCH_INDEX="https://download.pytorch.org/whl/cpu"
else
    log "Detected CUDA $CUDA_VER"
    PYTORCH_INDEX=$(resolve_pytorch_index "$CUDA_VER")
fi
log "PyTorch index: $PYTORCH_INDEX"

"$VENV_AI/bin/pip" install --quiet \
    torch torchvision torchaudio \
    --index-url "$PYTORCH_INDEX"

log "Verifying PyTorch..."
"$VENV_AI/bin/python3" -c "
import torch
print(f'  PyTorch {torch.__version__}')
print(f'  CUDA available: {torch.cuda.is_available()}')
if torch.cuda.is_available():
    print(f'  CUDA version: {torch.version.cuda}')
    print(f'  GPU: {torch.cuda.get_device_name(0)}')
" || warn "PyTorch verification script failed (non-fatal)."

# ── 9. vLLM-Omni venv + HuggingFace CLI ──────────────────────────────────────
step "vLLM-Omni venv"

VENV_VLLM="${VLLM_VENV/#\~/$HOME}"
if [[ -d "$VENV_VLLM" ]]; then
    log "vLLM-Omni venv already exists: $VENV_VLLM"
else
    log "Creating vLLM-Omni venv: $VENV_VLLM"
    mkdir -p "$(dirname "$VENV_VLLM")"
    python3 -m venv "$VENV_VLLM"
fi

"$VENV_VLLM/bin/pip" install --quiet --upgrade pip

log "Installing HuggingFace CLI + autoawq in vLLM-Omni venv..."
"$VENV_VLLM/bin/pip" install --quiet \
    "huggingface_hub[cli]" \
    autoawq \
    || warn "HuggingFace CLI / autoawq install failed (non-fatal)."

log "HuggingFace CLI installed. Token will be prompted lazily on first download."

# ── 10. CUDA 13.0 toolchain for vLLM / Bitwig agent ─────────────────────────
step "CUDA ${VLLM_CUDA_VERSION} toolchain"

find_cuda_version_path() {
    local target_ver="$1"
    # Check /usr/local/cuda-X.Y symlink/dir
    for p in "/usr/local/cuda-${target_ver}" "/usr/local/cuda"; do
        if [[ -x "${p}/bin/nvcc" ]]; then
            local found_ver
            found_ver=$("${p}/bin/nvcc" --version | grep -oP 'release \K[\d.]+' | head -1)
            if [[ "$found_ver" == "$target_ver"* ]]; then
                echo "$p"
                return 0
            fi
        fi
    done
    return 1
}

CUDA_132_PATH=""
if CUDA_132_PATH=$(find_cuda_version_path "$VLLM_CUDA_VERSION"); then
    log "CUDA ${VLLM_CUDA_VERSION} found at: $CUDA_132_PATH"
else
    log "CUDA ${VLLM_CUDA_VERSION} not found. Attempting installation..."

    # Try dnf first (Nobara/Fedora may have it)
    CUDA_MAJOR=$(echo "$VLLM_CUDA_VERSION" | cut -d. -f1)
    CUDA_MINOR=$(echo "$VLLM_CUDA_VERSION" | cut -d. -f2)
    CUDA_PKG="cuda-toolkit-${CUDA_MAJOR}-${CUDA_MINOR}"

    if have_passwordless_sudo && sudo dnf install -y "$CUDA_PKG" 2>/dev/null; then
        log "Installed $CUDA_PKG via dnf."
    else
        if ! have_passwordless_sudo; then
            die "CUDA ${VLLM_CUDA_VERSION} is missing and passwordless sudo is not available in first-login context. Install CUDA ${VLLM_CUDA_VERSION} manually or via first-boot, then re-run."
        fi
        # Fall back to NVIDIA runfile installer (side-by-side, no system CUDA overwrite)
        log "dnf package not available. Downloading NVIDIA CUDA ${VLLM_CUDA_VERSION} runfile..."
        RUNFILE_URL="https://developer.download.nvidia.com/compute/cuda/${VLLM_CUDA_VERSION}/local_installers/cuda_${VLLM_CUDA_VERSION}_linux.run"
        RUNFILE="/tmp/cuda-${VLLM_CUDA_VERSION}-installer.run"

        curl -L --retry 5 --progress-bar -o "$RUNFILE" "$RUNFILE_URL" \
            || die "Failed to download CUDA ${VLLM_CUDA_VERSION} runfile from NVIDIA."

        chmod +x "$RUNFILE"
        sudo "$RUNFILE" \
            --silent \
            --toolkit \
            --toolkitpath="/usr/local/cuda-${VLLM_CUDA_VERSION}" \
            --no-opengl-libs \
            --override \
            || die "CUDA ${VLLM_CUDA_VERSION} runfile installation failed."

        rm -f "$RUNFILE"
        log "CUDA ${VLLM_CUDA_VERSION} installed to /usr/local/cuda-${VLLM_CUDA_VERSION}"
    fi

    CUDA_132_PATH=$(find_cuda_version_path "$VLLM_CUDA_VERSION") \
        || die "CUDA ${VLLM_CUDA_VERSION} still not found after installation."
fi

# Write venv activation hook to set CUDA 13.0 env for this venv
VENV_ACTIVATE_HOOK="${VENV_VLLM}/bin/activate.d"
mkdir -p "$VENV_ACTIVATE_HOOK"
cat > "${VENV_VLLM}/bin/activate.cuda" <<HOOKEOF
# Auto-sourced for vLLM-Omni venv — sets CUDA ${VLLM_CUDA_VERSION} paths
export CUDA_HOME="${CUDA_132_PATH}"
export PATH="\${CUDA_HOME}/bin\${PATH:+:\$PATH}"
export LD_LIBRARY_PATH="\${CUDA_HOME}/lib64\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
HOOKEOF

# Inject into venv's activate script
if ! grep -q 'activate.cuda' "${VENV_VLLM}/bin/activate"; then
    echo '' >> "${VENV_VLLM}/bin/activate"
    echo '# Nobara: CUDA toolchain for vLLM-Omni' >> "${VENV_VLLM}/bin/activate"
    echo "source \"${VENV_VLLM}/bin/activate.cuda\"" >> "${VENV_VLLM}/bin/activate"
fi
log "CUDA ${VLLM_CUDA_VERSION} environment configured for venv: $VENV_VLLM"

# ── 11. vLLM-Omni source build ────────────────────────────────────────────────
step "vLLM-Omni source build (CUDA ${VLLM_CUDA_VERSION}, sm${VLLM_ARCH_LIST//./})"

VLLM_OMNI_SRC="${HOME}/.local/src/vllm-omni"

if [[ -d "${VLLM_OMNI_SRC}/.git" ]]; then
    log "vLLM-Omni source already cloned. Pulling latest..."
    git -C "$VLLM_OMNI_SRC" pull --ff-only || warn "git pull failed; using existing source."
else
    log "Cloning vLLM-Omni..."
    mkdir -p "$(dirname "$VLLM_OMNI_SRC")"
    git clone --depth=1 https://github.com/vllm-project/vllm.git "$VLLM_OMNI_SRC" \
        || die "Failed to clone vLLM-Omni."
fi

# Apply use_existing_torch.py to prevent overwriting the system PyTorch
if [[ -f "${VLLM_OMNI_SRC}/use_existing_torch.py" ]]; then
    log "Running use_existing_torch.py (protects external PyTorch installations)..."
    (cd "$VLLM_OMNI_SRC" && "$VENV_VLLM/bin/python3" use_existing_torch.py) \
        || warn "use_existing_torch.py failed (non-fatal, continuing build)."
fi

log "Building vLLM-Omni against CUDA ${VLLM_CUDA_VERSION} + sm${VLLM_ARCH_LIST//./}..."
(
    cd "$VLLM_OMNI_SRC"
    # Activate venv environment for build
    source "${VENV_VLLM}/bin/activate"
    source "${VENV_VLLM}/bin/activate.cuda"

    export TORCH_CUDA_ARCH_LIST="${VLLM_ARCH_LIST}"
    export CUDA_HOME="${CUDA_132_PATH}"
    export MAX_JOBS="${MAX_JOBS:-$(nproc)}"

    pip install --quiet --no-build-isolation . \
        || die "vLLM-Omni build failed."
)
log "vLLM-Omni build completed."

# ── 12. Download model ────────────────────────────────────────────────────────
step "Model download: ${VLLM_MODEL}"

log "Checking HuggingFace login..."
log "Downloading model: ${VLLM_MODEL} ..."
# Lazy token behavior: download will prompt for login only when required.
"$VENV_VLLM/bin/huggingface-cli" download "${VLLM_MODEL}" \
    --local-dir "${HOME}/.cache/huggingface/hub/${VLLM_MODEL//\//__}" \
    || warn "Model download failed or deferred (check HF token / disk space)."

# ── Final report ──────────────────────────────────────────────────────────────
step "First-login provisioning complete"

if [[ "${#WHITESUR_ERRORS[@]}" -gt 0 ]]; then
    warn "WhiteSur errors encountered:"
    for e in "${WHITESUR_ERRORS[@]}"; do
        warn "  - $e"
    done
fi

touch "$MARKER_FILE"
log "Marker written: $MARKER_FILE"

# Remove autostart entry — we're done
rm -f "${HOME}/.config/autostart/nobara-first-login.desktop"
log "Autostart entry removed."
log "First-login provisioning finished. Log: $LOG_FILE"

FLEOF
chmod 0755 /usr/local/bin/nobara-first-login.sh

# ── Write systemd unit for first-boot ────────────────────────────────────────
cat > /etc/systemd/system/nobara-first-boot.service <<'UNITEOF'
[Unit]
Description=Nobara First-Boot Provisioning (one-shot)
Documentation=https://github.com/user/nobara-install
After=network-online.target
Wants=network-online.target
# Ensure this runs only on first boot; marker file disables it on subsequent boots
ConditionPathExists=!/var/lib/nobara-provision/first-boot.done

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/nobara-first-boot.sh
EnvironmentFile=-/etc/nobara-provision.env
StandardOutput=journal+console
StandardError=journal+console
TimeoutStartSec=3600
RemainAfterExit=yes

# Prevent privilege escalation
NoNewPrivileges=no
# Service runs as root (required for dnf, systemctl, akmods)
User=root

[Install]
WantedBy=multi-user.target

UNITEOF

systemctl enable nobara-first-boot.service

# ── Install Extension Manager (Flatpak) at system level ──────────────────────
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo 2>/dev/null || true

# ── Configure first-login autorun for target user ────────────────────────────
USER_HOME="/home/sija"
AUTOSTART_DIR="$USER_HOME/.config/autostart"
mkdir -p "$AUTOSTART_DIR"
cat > "$AUTOSTART_DIR/nobara-first-login.desktop" <<'DESKTOPEOF'
[Desktop Entry]
Type=Application
Name=Nobara First-Login Setup
Exec=/usr/local/bin/nobara-first-login.sh
Hidden=false
NoDisplay=true
X-GNOME-Autostart-enabled=true
DESKTOPEOF
chown -R sija:sija "$AUTOSTART_DIR"

%end
